[package]
name = "boa"
description = "Milking the mincut-maxflow cow."
version = "0.1.0"
repository = "https://github.com/ahimta/lop"
edition = "2018"
authors = ["Abdullah Alansari <ahimta@gmail.com>"]
license = "GPLv3"
readme = "../README.md"
keywords = ["mincut", "maxflow", "sports"]
categories = ["algorithms", "data-structures", "games", "mathematics", "simulation"]

[lib]
# SEE: https://doc.rust-lang.org/reference/linkage.html
crate-type   = ["rlib", "staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = "0.0.302"
