name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    # SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Continuous Integration
        # NOTE: We use Docker instead of Podman here because there doesn't seem
        # to be a supported way to use Podman in GitHub Actions.
        run: |
          CONTAINER_COMMAND=docker PRE_COMMIT_CHECK=1 RUN_IN_CONTAINER=1 ./scripts/continuous-integration.sh
