name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Continuous Integration
        # NOTE: We use Docker instead of Podman here because there doesn't seem
        # to be a supported way to use Podman in GitHub Actions
        run: |
          RUN_IN_CONTAINER=1 ./scripts/continuous-integration.sh docker
