name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Continuous Integration
      run: ./scripts/continuous-integration.sh
