name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Continuous Integration
      run: |
        docker build --tag lop --file ./Containerfile .
        docker run --mount type=bind,src="$PWD",dst=/project --rm --user "$(id --user):$(id --group)" --workdir /project lop
